### ISSUE TITLE
开始提示“文件解密失败”

### ISSUE THREAD

**Issue by pdxadp** [flucont/btcloud#126]
之前都是正常的
今天手动重新下载插件，突然开始提示“解密插件主程序文件失败：文件解密失败”，所有付费插件均如此
（我用的bt.sy开心版作为面板接口）

**Comment by xs77xs** [comment]
解决了吗？ 我也是这样

**Comment by pdxadp** [comment]
> 解决了吗？ 我也是这样

解决了，init.sh加上api地址

**Comment by cuicsi** [comment]
> 

可以详细说一下怎么操作吗，谢谢了🌟🙏✌️

**Comment by pdxadp** [comment]
> > 
> 
> 可以详细说一下怎么操作吗，谢谢了🌟🙏✌️

如果是bt.sy的话，在`/www/server/panel/init.sh`这个文件里面顶部注释，随便找个地方粘贴`//api.bt.sy/`就好了

**Comment by cuicsi** [comment]
收到，谢谢

**Comment by xs77xs** [comment]
> > 解决了吗？ 我也是这样
> 
> 
> 
> 解决了，init.sh加上api地址

怎么添加的  方便复制出来吗？

**Comment by emengweb** [comment]
解决了，谢谢！

> > > 
> > 
> > 
> > 可以详细说一下怎么操作吗，谢谢了🌟🙏✌️
> 
> 如果是bt.sy的话，在`/www/server/panel/init.sh`这个文件里面顶部注释，随便找个地方粘贴`//api.bt.sy/`就好了
