### ISSUE TITLE
自己怎么搞8.0.2的文件

### ISSUE THREAD

**Issue by huolangwangluo** [flucont/btcloud#133]
宝塔官方没推送 对接的一个开心版升级了 我也想给升级8.0.2

**Comment by jacky06046** [comment]
http://download.bt.cn/install/update/LinuxPanel-8.0.2.zip

**Comment by huolangwangluo** [comment]
> http://download.bt.cn/install/update/LinuxPanel-8.0.2.zip

除了把宝塔的下载地址改了其他的不用变？

**Comment by jacky06046** [comment]
> > http://download.bt.cn/install/update/LinuxPanel-8.0.2.zip
> 
> 除了把宝塔的下载地址改了其他的不用变？

https://github.com/flucont/btcloud/blob/main/wiki/update.md

這裡有教學

**Comment by huolangwangluo** [comment]
> > > http://download.bt.cn/install/update/LinuxPanel-8.0.2.zip
> > 
> > 
> > 除了把宝塔的下载地址改了其他的不用变？
> 
> https://github.com/flucont/btcloud/blob/main/wiki/update.md
> 
> 這裡有教學

PluginLoader.py这个文件没找到

**Comment by jacky06046** [comment]
> 

https://github.com/flucont/btcloud/tree/f5c255bd185617ede5ec03a373e998f001c6956d/wiki/files/linux

在這裡喔

**Comment by jacky06046** [comment]
> > > > http://download.bt.cn/install/update/LinuxPanel-8.0.2.zip
> > > 
> > > 
> > > 除了把宝塔的下载地址改了其他的不用变？
> > 
> > 
> > https://github.com/flucont/btcloud/blob/main/wiki/update.md
> > 這裡有教學
> 
> PluginLoader.py这个文件没找到

https://github.com/flucont/btcloud/tree/f5c255bd185617ede5ec03a373e998f001c6956d/wiki/files/linux

在這裡喔

**Comment by huolangwangluo** [comment]
> 官方没推送说明官方认为可能不稳定，等bug修的差不多了再更新。

服务器都快到期了 稳定不稳定那重要吗
