### ISSUE TITLE
8.0.3报错

### ISSUE THREAD

**Issue by linke131** [flucont/btcloud#146]
![IMG_20231107_010204](https://github.com/flucont/btcloud/assets/145977871/27ad026c-d77c-45f9-ac10-122ef7c23f93)
![IMG_20231107_010225](https://github.com/flucont/btcloud/assets/145977871/7fcff450-96ea-450b-8af4-f6025e8a57c6)
![Screenshot_20231107_010319](https://github.com/flucont/btcloud/assets/145977871/5fb3b9eb-344d-4623-8d26-424296a4a898)
软件商店空白

**Comment by magicjiaxia** [comment]
你开了白名单。需要加入白名单

**Comment by linke131** [comment]
> 你开了白名单。需要加入白名单

OK了   我看了默认好像没开   我手动开了在关闭就好了不知道是不是属于bug
