### ISSUE TITLE
插件无法显示历史版本

### ISSUE THREAD

**Issue by emengweb** [flucont/btcloud#16]
无法显示历史版本，也无法选择历史版本的插件进行安装

**Comment by emengweb** [comment]
另外，未购买的插件，商店列表里也不显示，希望可以优化下呢

**Comment by flucont** [comment]
具体显示哪些历史版本和官方的一样。

**Comment by emengweb** [comment]
现在安装插件时，点击历史版本出现空白
![image](https://user-images.githubusercontent.com/31469739/172997083-6dcbf2c6-dcbf-4a72-993b-8c1552cb2c05.png)
