### ISSUE TITLE
8.0.5版本判断好像变了

### ISSUE THREAD

**Issue by jeitao** [flucont/btcloud#165]
目前云端安装的，会按实际授权地址以及版本来。

不会直接显示企业版+10年了。

**Comment by zhaxidelei789** [comment]
比如对接的是专业版的api，那安装后的就是专业版而不是和以前一样默认显示企业版吗

**Comment by jeitao** [comment]
> 比如对接的是专业版的api，那安装后的就是专业版而不是和以前一样默认显示企业版吗



> 比如对接的是专业版的api，那安装后的就是专业版而不是和以前一样默认显示企业版吗

对的。然后一些企业版才能用的功能就不能用了。

**Comment by zhaxidelei789** [comment]
> 我刚才试了，并不会这样，还是一样10年

刚才我也遇到了一次变成了专业版，并非新安装的宝塔，我用的8.0.4，过了一会又变回企业版了，触发原因未知

**Comment by skwax** [comment]
ssh 修复一下面板就行

**Comment by jeitao** [comment]
> ssh 修复一下面板就行

我这里修复了也没用。依然是原来授权的日期和版本。退回8.0.4就是正常的。

**Comment by jeitao** [comment]
已有同类问题。我这个关了
