### ISSUE TITLE
8.0.5 nginx 配置文件多了个;

### ISSUE THREAD

**Issue by cdnov** [flucont/btcloud#166]
nginx: [emerg] unexpected ";" in /www/server/panel/vhost/nginx/0.default.conf:6
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by jeitao** [comment]
不想重装的可以：
/www/server/panel/vhost/nginx/0.default.conf
第六行      return 400;;    去掉后面这个多余的分号即可。
