### ISSUE TITLE
9.1版本发布了 求更新， 还有最新版本无法安装第三方插件。

### ISSUE THREAD

**Issue by mengshenlio** [flucont/btcloud#199]
8.2.0(20240702)版本第三方插件全部没办法安装， 安装的时候提示什么无法安装。第三方免费的插件也不行， 只有这个版本是这样， 退回其他的版本就可以安装了。
大佬更新9.1版本的时候留意一下这个问题哈 。

**Comment by cfcch** [comment]
网站-反向代理： 报  模块[proxy/com]不存在  错误，官方版不报错

**Comment by mengshenlio** [comment]
> 没有啊，我试了这个版本，第三方插件都可以安装

 额，我这边9.10和最新的8.20都不行， 提示不支持当前操作，大佬看看什么问题，      我退回以前的8.20版本以下的版本都没有这个问题。

**Comment by mengshenlio** [comment]
![image](https://github.com/user-attachments/assets/b00fffbc-c104-49e1-8826-6eb039bae831)


> 没有啊，我试了这个版本，第三方插件都可以安装

![image](https://github.com/user-attachments/assets/d99d38d5-f63d-4862-924b-750914ff8e97)
如图， 只有这俩个版本这样提示 以前的版本没有这个问题。

**Comment by mengshenlio** [comment]
> 没有啊,我试了这个版本,第三方插件都可以安装

新的9.10版本也有这个问题额。退回原来的老版8.20版本反而好了。   插件云端已经都安装了。所有第三方插件安装都报这个。

**Comment by mengshenlio** [comment]
> 8.2.0(20240702)版本第三方插件全部没办法安装， 安装的时候提示什么无法安装。第三方免费的插件也不行， 只有这个版本是这样， 退回其他的版本就可以安装了。 大佬更新9.1版本的时候留意一下这个问题哈 。
