### ISSUE TITLE
开心破解

### ISSUE THREAD

**Issue by ZianTT** [flucont/btcloud#2]
希望大佬能不能顺带做一下破解，使其能直接下载付费插件？

**Comment by flucont** [comment]
我也没买专业版，没法下载专业版的插件

**Comment by zephyr-y** [comment]
有专业版的下载后，打包共享，是不是大家都可以用了？

**Comment by ZianTT** [comment]
> 有专业版的下载后，打包共享，是不是大家都可以用了？

理论上确实如此，但是我在想如果云端面板装的是开心版的话是不是可以完美pj了？

**Comment by izhuolin** [comment]
> > 有专业版的下载后，打包共享，是不是大家都可以用了？>>理论上确实如此，但我在想如果云端面板装是开心版的话是不是可以完美pj了？
这个我已经试过了没有用插件可以下载 但是绝大部分插件无法使用

**Comment by ZianTT** [comment]
确实，因为解密逻辑不同，所以下载下来的理论上全部无法解密，理论全部不能用
但是有另外的解决办法：
将这个目录下的内容上传到/data/plugins/packages，这些都是解密过的，所以客户端调用下载的就是他们，然后不就能做到了
https://github.com/Tmitsuha/panel/tree/main/plugin




------------------&nbsp;原始邮件&nbsp;------------------


   
有专业版的下载后，打包共享，是不是大家都可以用了？&gt;&gt;理论上确实如此，但我在想如果云端面板装是开心版的话是不是可以完美pj了？
 这个我已经试过了没有用插件可以下载 但是绝大部分插件无法使用

**Comment by izhuolin** [comment]
> 你真是我的好大哥 我因为这个研究一天了

**Comment by izhuolin** [comment]
> 确实，因为解密逻辑不同，所以下载下来的理论上全部无法解密，理论全部不能用 但是有另外的解决办法： 将这个目录下的内容上传到/data/plugins/packages，这些都是解密过的，所以客户端调用下载的就是他们，然后不就能做到了 https://github.com/Tmitsuha/panel/tree/main/plugin
> […](#)
🐮 好大哥 谢谢 我研究插件研究的心态爆炸
