### ISSUE TITLE
Undefined variable $cdnpublic

### ISSUE THREAD

**Issue by wantsir** [flucont/btcloud#211]
Undefined variable $cdnpublic

[ThinkPHP](http://www.thinkphp.cn/) V6.1.4 { 十年磨一剑-为API开发设计的高性能框架 } - [官方手册](https://www.kancloud.cn/manual/thinkphp6_0/content)

v2.7和v2.7.1都提示这个，无法安装，请修复下，谢谢(v2.6正常)。

**Comment by skyle1995** [comment]
![1725676689029](https://github.com/user-attachments/assets/37e3efe3-5c03-4844-9d1b-27c13e72fe74)
缺少引用定义，自己定义一个就行了

**Comment by skyle1995** [comment]
![1725677422687](https://github.com/user-attachments/assets/7acb2caf-b445-417d-9d26-2a3e2178ddb6)
改一下模板的静态文件引用就行

**Comment by wantsir** [comment]
谢谢各位，已测，可以了。
