### ISSUE TITLE
7.9.3无法改面板别名等信息

### ISSUE THREAD

**Issue by douya520** [flucont/btcloud#31]
提示超时时间不能为空。实际是有设置时间的。回滚7.9.2是正常的。

不知道是不是我一个人的问题。有人能测试看看吗？

**Comment by flucont** [comment]
我这试了没出现你说的问题

**Comment by douya520** [comment]
乌龙了。原来是刚升级静态资源有缓存。

过一会/隐私模式打开就没问题了。
