### ISSUE TITLE
下载的最新的1.1.3还是有错误提示

### ISSUE THREAD

**Issue by oyh196** [flucont/btcloud#42]
Traceback (most recent call last):
  File "/www/server/panel/BTPanel/__init__.py", line 1774, in publicObject
    return run_exec().run(toObject, defs, get)
  File "/www/server/panel/BTPanel/__init__.py", line 1722, in run
    result = getattr(toObject,get.action)(get)
  File "class/panelPlugin.py", line 1329, in get_index_list
    softList = self.get_cloud_list(get)['list']
  File "class/panelPlugin.py", line 957, in get_cloud_list
    softList = Plugin(False).get_plugin_list(force)
  File "class/pluginAuth.py", line 45, in get_plugin_list
    return PluginLoader.get_plugin_list(force)
  File "class/PluginLoader.py", line 18, in get_plugin_list
    softList = json.loads(jsonData)
  File "/www/server/panel/pyenv/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not bool

**Comment by CollinsWalker** [comment]
我也是这个问题，但是执行一下更新就没事了，更新完变成企业版了:)
ps：(flucont抱歉大佬没玩懂git貌似好像整了一个pull requests，抱歉哈)

**Comment by CollinsWalker** [comment]
> Traceback (most recent call last): File "/www/server/panel/BTPanel/**init**.py", line 1774, in publicObject return run_exec().run(toObject, defs, get) File "/www/server/panel/BTPanel/**init**.py", line 1722, in run result = getattr(toObject,get.action)(get) File "class/panelPlugin.py", line 1329, in get_index_list softList = self.get_cloud_list(get)['list'] File "class/panelPlugin.py", line 957, in get_cloud_list softList = Plugin(False).get_plugin_list(force) File "class/pluginAuth.py", line 45, in get_plugin_list return PluginLoader.get_plugin_list(force) File "class/PluginLoader.py", line 18, in get_plugin_list softList = json.loads(jsonData) File "/www/server/panel/pyenv/lib/python3.7/json/**init**.py", line 341, in loads raise TypeError(f'the JSON object must be str, bytes or bytearray, ' TypeError: the JSON object must be str, bytes or bytearray, not bool

plugin_list.json缺少这个文件，加到`/www/server/panel/data`这个目录下即可

**Comment by jxcxin** [comment]
云端后台重新获取一下软件列表就行了

**Comment by oyh196** [comment]
谢谢，解决了
