### ISSUE TITLE
使用中遇到的问题

### ISSUE THREAD

**Issue by lingyuanzhicheng** [flucont/btcloud#43]
1. 第三方插件导入报错
![image](https://user-images.githubusercontent.com/72078405/182342540-06917493-c3da-4acb-97c7-beafa6cf8d0c.png)
宝塔Linux面板企业版7.9.3。导入第三方插件后，插件报错。在以前7.9.2中正常。

2. 后台更新插件列表后，点击未下载的插件，手动下载大多数都会显示解密插件解密失败。显示解密失败后后台插件版本按钮显示是绿色，未解密插件zip文件有时会出现在data/plugin目录内，有时没有。

以上两个问题中，导入第三方插件用于获取官方最新插件的服务器与搭建了btcloud程序的服务器不是同一个。

**Comment by flucont** [comment]
1.我用的官方最新版7.9.3导入插件没出现你说的提示
2.插件安装好之后，都可以解密成功，没有提示解密失败的。显示解密失败后后台插件版本按钮显示是绿色是正常的，再次点击可以重试。

**Comment by lingyuanzhicheng** [comment]
已经解决，是我以前把宝塔面板的文件改过，宝塔面板文件受损了。我修复后就正常了。两个问题就都没有了。
