### ISSUE TITLE
docker页面打开提示需要企业版

### ISSUE THREAD

**Issue by skyle1995** [flucont/btcloud#46]
看提示，能修复一下吗
![CFT 5B52K%{PUSI4Y8~IC}M](https://user-images.githubusercontent.com/39904228/184851977-0584b84f-ccf3-477b-b4f0-b8ee3e52684d.png)

**Comment by skyle1995** [comment]
已经自行修复

**Comment by duiaic** [comment]
> 



> 已经自行修复

如何修复？

**Comment by skyle1995** [comment]
> 

手动下载官方最新版本，然后自己制作新的安装包

**Comment by skyle1995** [comment]
> > 
> 
> > 已经自行修复
> 
> 如何修复？

手动下载官方最新版本，然后自己制作新的安装包

**Comment by skyle1995** [comment]
我自己写了一个电脑版的替换工具：https://github.com/skyle1995/btcloud/blob/main/wiki/files/%E6%9B%BF%E6%8D%A2.exe
