### ISSUE TITLE
通过docker部署的会出现显示不了验证码的情况

### ISSUE THREAD

**Issue by ayanami-desu** [flucont/btcloud#5]
请问可能在哪个地方出了问题，启用了.env中的app_debug也没找到有用的报错日志
我猜测可能的原因：没有启用ziparchieve；没有安装验证码拓展

**Comment by flucont** [comment]
应该是没有安装php用的GD类库

**Comment by ayanami-desu** [comment]
```#0 [0]Error in Captcha.php line 181
Call to undefined function think\captcha\imagecreate()

Call Stack
in Captcha.php line 181
at Captcha->create(null)
at call_user_func_array([object(Captcha), 'create'], [null]) in Facade.php line 96
at Facade::__callStatic('create', [null]) in helper.php line 22
at captcha() in Admin.php line 16
at Admin->verifycode()
at ReflectionMethod->invokeArgs(object(Admin), []) in Container.php line 344```
…………
…………

找到了详细的报错日志

**Comment by emengweb** [comment]
求一个可以docker部署的镜像，谢谢(*°∀°)=3

**Comment by captainstdin** [comment]
> 求一个可以docker部署的镜像，谢谢(*°∀°)=3

我已写好了, 有email联系下？

**Comment by captainstdin** [comment]
> 求一个可以docker部署的镜像，谢谢(*°∀°)=3


Dockerfile:
`
FROM alpine:latest
#安装init
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
	&& apk update \
    && apk add git wget curl nload php8-cli php8-redis php8-pcntl php8-posix php8-iconv php8-pdo php8-gd php8-pdo_mysql php8-zip php8-gd php8-fileinfo \
      php8-pecl-event  php8-curl php8-json php8-xml  php8-openssl   php8-mysqli php8-common php8-ctype php8-phar php8-mbstring php8-bcmath  \
    && ln -s /usr/bin/php8 /usr/bin/php \
    && php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && php composer.phar config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    && ln -s /app/composer.phar /usr/bin/composer


WORKDIR /app
#COPY / /app

RUN   mkdir -p /tmp/logs \
      && mkdir -p /tmp/sessions \
      && mkdir -p /tmp/views \
      && rm -rf /app/runtime \
      && ln -s /tmp  /app/runtime

#暴露 http 
EXPOSE 8000
VOLUME /app


CMD ["php","/app/think","run"]

# docker build -t dtmachine:latest .
# docker run -it -p8080:8000   youBuildName
`

docker-composer:
`version: "3.0"
services:
  dtmachine:
    build: ./
    ports:
      - "8000:88"
    volumes:
      - ./:/app/   #宿主机：容器
    dns:
      - 223.5.5.5
      - 223.6.6.6
    depends_on:
      - mariadb
    networks:
      - dtmachine-network
        
  mariadb:
    image: qqfirst/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      ROOT_PASSWORD : "123456"
      DATABASE : "bt"
    volumes:
      - ./mysql:/var/lib/mysql
    dns: 
      - 223.5.5.5
      - 223.6.6.6
    networks:
      - dtmachine-network

networks:
  dtmachine-network:
    # driver:  custom-driver-1`

**Comment by emengweb** [comment]
> 

docker-composer YYDS!

**Comment by emengweb** [comment]
> 

容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
```PHP Warning:  require(/app/vendor/autoload.php): Failed to open stream: No such file or directory in /app/think on line 7
PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
Stack trace:
#0 {main}
  thrown in /app/think on line 7```

**Comment by captainstdin** [comment]
> > 
> 
> 容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
> 
> ```
> PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
> Stack trace:
> #0 {main}
>   thrown in /app/think on line 7```
> ```

composer没有拉取，我写忘了

docker exec  container_name  php /app/composer.phar install

或者 dockerfile 中追加


~~~

RUN php /app/composer.phar install
WORKDIR /app
#COPY / /app
~~~

**Comment by emengweb** [comment]
> > > 
> > 
> > 
> > 容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
> > ```
> > PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
> > Stack trace:
> > #0 {main}
> >   thrown in /app/think on line 7```
> > ```
> 
> composer没有拉取，我写忘了
> 
> docker exec -it container_name php /app/composer.phar install
> 
> 或者 dockerfile 中追加
> 
> ```
> 
> RUN php /app/composer.phar install
> WORKDIR /app
> #COPY / /app
> ```

添加了，依旧提示找不到文件。。。这是我修改后的dockerfile

```
FROM alpine:latest
#安装init
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
	&& apk update \
    && apk add git wget curl nload php8-cli php8-redis php8-pcntl php8-posix php8-iconv php8-pdo php8-gd php8-pdo_mysql php8-zip php8-gd php8-fileinfo \
      php8-pecl-event  php8-curl php8-json php8-xml  php8-openssl   php8-mysqli php8-common php8-ctype php8-phar php8-mbstring php8-bcmath
RUN ln -sf /usr/bin/php8 /usr/bin/php \
    && php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && php composer.phar config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    && ln -s /app/composer.phar /usr/bin/composer

#RUN php /app/composer.phar install
WORKDIR /app
#COPY / /app

RUN   mkdir -p /tmp/logs \
      && mkdir -p /tmp/sessions \
      && mkdir -p /tmp/views \
      && rm -rf /app/runtime \
      && ln -s /tmp  /app/runtime

#暴露 http 
EXPOSE 8000
VOLUME /app

CMD ["php","/usr/bin/composer","install","--no-dev"]
CMD ["php","/app/think","run"]


# docker build -t dtmachine:latest .
# docker run -it -p8080:8000   youBuildName

```

**Comment by emengweb** [comment]
搞定了，使用Release版本替换了clone的源文件，禁用了`CMD ["php","/usr/bin/composer","install","--no-dev"]`，还将所有程序文件都移动到project目录下 问题解决了，还差一步自动初始化数据库，我去查查资料

**Comment by captainstdin** [comment]
> > > > 
> > > 
> > > 
> > > 容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
> > > ```
> > > PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
> > > Stack trace:
> > > #0 {main}
> > >   thrown in /app/think on line 7```
> > > ```
> > 
> > 
> > composer没有拉取，我写忘了
> > docker exec -it container_name php /app/composer.phar install
> > 或者 dockerfile 中追加
> > ```
> > 
> > RUN php /app/composer.phar install
> > WORKDIR /app
> > #COPY / /app
> > ```
> 
> 定位到问题了，进入到容器内访问8000端口的服务是正常的。 最后居然是端口映射到88上导致的，修改docker-compose.yml端口8000就好了 😂
> 
> ```
>     ports:
>       - 8000:8000
> ```
> 
> 数据库也配置好了，端口直接访问后提示`ERR_EMPTY_RESPONSE`，curl访问也报错
> 
> ```
> # curl 127.0.0.1:8000/admin
> curl: (56) Recv failure: Connection reset by peer
> ```
> 
> 这是dtmachine的日志，求指点T.T：
> 
> ```
> ThinkPHP Development server is started On 
> You can exit with `CTRL-C`
> Document root is: /app/public
> [Wed Jun  8 08:27:44 2022] PHP 8.0.19 Development Server (http://0.0.0.0:8000) started
> ```

私聊下联系方式吧？adminv@88.com，我是宝塔装不上，所以没测试。

**Comment by emengweb** [comment]
> > > > 
> > > 
> > > 
> > > 容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
> > > ```
> > > PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
> > > Stack trace:
> > > #0 {main}
> > >   thrown in /app/think on line 7```
> > > ```
> > 
> > 
> > composer没有拉取，我写忘了
> > docker exec -it container_name php /app/composer.phar install
> > 或者 dockerfile 中追加
> > ```
> > 
> > RUN php /app/composer.phar install
> > WORKDIR /app
> > #COPY / /app
> > ```
> 
> 数据库也配置好了，端口直接访问后提示`ERR_EMPTY_RESPONSE`，curl访问也报错
> 
> ```
> # curl 127.0.0.1:8000/admin
> curl: (56) Recv failure: Connection reset by peer
> ```
> 
> 这是dtmachine的日志，求指点T.T：
> 
> ```
> ThinkPHP Development server is started On 
> You can exit with `CTRL-C`
> Document root is: /app/public
> [Wed Jun  8 08:27:44 2022] PHP 8.0.19 Development Server (http://0.0.0.0:8000) started
> ```



> > > > > 
> > > > 
> > > > 
> > > > 容器启动失败，提示找不到文件，奇怪，Dockerfile明明放在btcloud目录下，也开了映射的，求指点
> > > > ```
> > > > PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/think:7
> > > > Stack trace:
> > > > #0 {main}
> > > >   thrown in /app/think on line 7```
> > > > ```
> > > 
> > > 
> > > composer没有拉取，我写忘了
> > > docker exec -it container_name php /app/composer.phar install
> > > 或者 dockerfile 中追加
> > > ```
> > > 
> > > RUN php /app/composer.phar install
> > > WORKDIR /app
> > > #COPY / /app
> > > ```
> > 
> > 
> > 定位到问题了，进入到容器内访问8000端口的服务是正常的。 最后居然是端口映射到88上导致的，修改docker-compose.yml端口8000就好了 😂
> > ```
> >     ports:
> >       - 8000:8000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 数据库也配置好了，端口直接访问后提示`ERR_EMPTY_RESPONSE`，curl访问也报错
> > ```
> > # curl 127.0.0.1:8000/admin
> > curl: (56) Recv failure: Connection reset by peer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是dtmachine的日志，求指点T.T：
> > ```
> > ThinkPHP Development server is started On 
> > You can exit with `CTRL-C`
> > Document root is: /app/public
> > [Wed Jun  8 08:27:44 2022] PHP 8.0.19 Development Server (http://0.0.0.0:8000) started
> > ```
> 
> 私聊下联系方式吧？[adminv@88.com](mailto:adminv@88.com)，我是宝塔装不上，所以没测试。

联系你啦～这个邮箱好厉害！
