### ISSUE TITLE
大佬求助,已经添加gd.so库,还是无法显示验证码

### ISSUE THREAD

**Issue by msycn** [flucont/btcloud#55]
PHP = 8.1
MySQL = 8.0
fileinfo扩展 已编译
ZipArchive扩展 编译

问题复现:
参照https://github.com/flucont/btcloud/issues/5   已经添加gd.so库,还是无法显示验证码
![photo_2022-09-30_22-47-27](https://user-images.githubusercontent.com/85003651/193380250-65b9bb33-9843-4e87-a767-ea83457f652e.jpg)

求帮助

**Comment by msycn** [comment]
[extension]
extension_dir = "/usr/local/php/lib/php/extensions/no-debug-non-zts-20210902/"
extension = gd.so
extension = fileinfo.so
extension = memcached.so
extension = opcache.so
extension = redis.so
extension = zip.so
php.ini 已上传
[php.txt](https://github.com/flucont/btcloud/files/9689425/php.txt)

**Comment by flucont** [comment]
你这个是每个库单独编译的so吗？反正用宝塔自带的php8.1没问题

**Comment by msycn** [comment]
> 你这个是每个库单独编译的so吗？反正用宝塔自带的php8.1没问题

是的,我用命令行编译的 应该不会会缺少库

**Comment by msycn** [comment]
> 宝塔自带的php8.1没问
 换了宝塔的vps还是一样, 排查了一下伪静态是不是不对
请问 thinkphp 是这样改吗
if (!-e $request_filename) {
        rewrite  ^(.*)$  /index.php?s=/$1  last;
        break;
    }

**Comment by msycn** [comment]
> 你这个是每个库单独编译的so吗？反正用宝塔自带的php8.1没问题

切换回php 7.4就好了,不支持8.1
