### ISSUE TITLE
执行"定时任务"出错

### ISSUE THREAD

**Issue by LjyLab** [flucont/btcloud#57]
![image](https://user-images.githubusercontent.com/36144129/198840212-493beeb4-a5f7-40e1-af3e-cd09dfb797a5.png)
请问一下各位大佬 这个PHP错误咋解决

**Comment by LoveesYe** [comment]
![@%QBYF_CF~_}3TC @7WICIJ](https://user-images.githubusercontent.com/109154433/198851342-4f0da162-ff29-4b3c-b4df-a04ffbe9041c.png)

很明显，你php.ini配置出错

**Comment by LjyLab** [comment]
![image](https://user-images.githubusercontent.com/36144129/198865440-6b659a20-a065-47fe-a4a3-dd797870daca.png)
现在是这样了 咋办 大佬
