### ISSUE TITLE
执行批量解密模块命令需要具备什么条件？

### ISSUE THREAD

**Issue by jxcxin** [flucont/btcloud#59]
按照Linux面板官方更新包修改记录，执行批量解密模块文件：执行 php think decrypt classdir <面板class文件夹路径>
终端提示Could not open input file: think

**Comment by ccfacai** [comment]
先进入API 的网站目录再执行 例如 php think decrypt classdir  /www/wwwroot/panel/class(对应你自己的目录修改)
