### ISSUE TITLE
debian11安装报错

### ISSUE THREAD

**Issue by wrnxr233** [flucont/btcloud#7]
cat: /etc/redhat-release: No such file or directory
install.sh: 29: [: Illegal number:
install.sh: 186: Syntax error: "(" unexpected (expecting "}")

**Comment by flucont** [comment]
debian的话要用bash命令安装，sh替换成bash

**Comment by wrnxr233** [comment]
目前跑起来了，感谢大佬

**Comment by wrnxr233** [comment]
打开面板报错TypeError: the JSON object must be str, bytes or bytearray, not bool
这是哪里没改对吗

**Comment by wrnxr233** [comment]
已解决，谢谢大佬的付出
