### ISSUE TITLE
云端面板开心版时无法解密插件

### ISSUE THREAD

**Issue by ZianTT** [flucont/btcloud#8]
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/53261506/172089394-e7a67e36-e3a9-4be2-912a-2cb112c6232c.png">

出错了，[宝塔第三方云端接口]运行时发生错误！

UnicodeDecodeError: 'gbk' codec can't decode byte 0xf9 in position 22: illegal multibyte sequence

REQUEST_DATE: 2022-06-06 11:21:18
 PAN_VERSION: 7.9.0
  OS_VERSION: CentOS  7.9.2009 x86_64(Py3.7.9)
 REMOTE_ADDR: 101.93.108.240
 REQUEST_URI: POST /plugin?request_time=14516064000&request_token=5b5af3c4f12164dad973957922d610c2&action=a&name=kaixin&s=decode_plugin_main&plugin_name=nodejs&version=1.6
REQUEST_FORM: {}
  USER_AGENT: Paw/3.3.3 (Macintosh; OS X/12.3.1) GCDHTTPRequest
Traceback (most recent call last):
  File "class/public.py", line 296, in ReadFile
    f_body = fp.read()
  File "/www/server/panel/pyenv/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 10: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "class/public.py", line 301, in ReadFile
    f_body = fp.read()
  File "/www/server/panel/pyenv/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 10: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pluginAuth.py", line 447, in pluginAuth.Plugin.exec_fun
  File "/www/server/panel/plugin/kaixin/kaixin_main.py", line 155, in decode_plugin_main
    src = public.readFile(plugin_bin)
  File "class/public.py", line 320, in readFile
    return ReadFile(filename,mode)
  File "class/public.py", line 304, in ReadFile
    f_body = fp.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xf9 in position 22: illegal multibyte sequence

**Comment by flucont** [comment]
这个开心版并没有集成官方的解密算法（在so里面）。但是既然是开心版，那应该是都已经解密好的，直接无视该错误就能用。

**Comment by ZianTT** [comment]
> 这个开心版并没有集成官方的解密算法（在so里面）。但是既然是开心版，那应该是都已经解密好的，直接无视该错误就能用。

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/53261506/172115219-00207d1b-40ac-4f3c-b10b-4b9ad33a6be3.png">
这似乎是没解密？

**Comment by flucont** [comment]
对，就是没解密

**Comment by ZianTT** [comment]
> 对，就是没解密

e，那大佬推荐一个能用的开心脚本？
